# Ex1 - Filtrar y ordenar datos

### Paso 1. Importar las bibliotecas necesarias

In [ ]:
import pandas as pd
import numpy as np
pd.__version__
np.__version__

### Paso 2. Importar el conjunto de datos de esta [dirección](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [118]:
url= 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep = '\t') #tiene de separador una tabulación

### Paso 3. Asígnalo a una variable llamada chipo.

In [119]:
len (chipo)
chipo.head (10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

# Nombre del producto de valor máximo

In [120]:
chipo.info() #vemos que item price es un objeto, no un float

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [158]:
chipo['item_price_float'] = chipo['item_price']     #replico la columna para transformarla
chipo['item_price_float'] = chipo['item_price_float'].str.strip().str.slice(start=1)

chipo['item_price_float'] = chipo['item_price_float'].astype('float32') #cambio el string por un flotante
chipo.head()

,order_id,quantity,item_name,choice_description,item_price,item_price_float
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
1,1,1,Izze,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98

In [126]:
chipo['item_price_float'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 4622 entries, 0 to 4621
Series name: item_price_float
Non-Null Count  Dtype
--------------  -----
4622 non-null   float32
dtypes: float32(1)
memory usage: 18.2 KB

In [142]:
max_price_item = chipo.loc[chipo['item_price_float'].idxmax(), 'item_name']

chipo['item_price_float'].max()
chipo['item_price_float'].idxmax()
print (f'el item con el precio más alto es {max_price_item}, con un precio de {chipo['item_price_float'].max()}, en la posición {chipo['item_price_float'].idxmax()}')

el item con el precio más alto es Chips and Fresh Tomato Salsa, con un precio de 44.25, en la posición 3598

*agv_en realidad, el precio más alto sucede porque el ticket tiene muchas unidades del item...
habría que dividirlo por el número de unidades*

In [187]:
chipo.sort_values('item_price_float', ascending=False)

,order_id,quantity,item_name,choice_description,item_price,item_price_float
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25,44.25
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25,35.25
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00,35.00
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00,35.00
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75,33.75
...,...,...,...,...,...,...
1057,435,1,Canned Soda,[Mountain Dew],$1.09,1.09
117,51,1,Canned Soda,[Diet Dr. Pepper],$1.09,1.09
2562,1014,1,Canned Soda,[Coca Cola],$1.09,1.09
2544,1009,1,Canned Soda,[Diet Coke],$1.09,1.09
2545,1009,1,Bottled Water,NaN,$1.09,1.09

In [133]:
#verificación
chipo.loc[3598,:]

order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                 $44.25
item_price_float                             44.25
Name: 3598, dtype: object

In [201]:
#si hacemos por el precio del item individual
chipo['unit_price'] = chipo['item_price_float'] / chipo['quantity']

# Localizao el índice del valor unitario más alto
max_unit_price_idx = chipo['unit_price'].idxmax()

chipo.sort_values('unit_price', ascending=False)

,order_id,quantity,item_name,choice_description,item_price,item_price_float,unit_price
2442,970,1,Barbacoa Salad Bowl,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.89,11.89,11.89
2439,969,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.89,11.89,11.89
2957,1176,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",$11.89,11.89,11.89
4313,1720,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.89,11.89,11.89
1816,734,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.89,11.89,11.89
...,...,...,...,...,...,...,...
1948,788,1,Canned Soda,[Dr. Pepper],$1.09,1.09,1.09
18,9,2,Canned Soda,[Sprite],$2.18,2.18,1.09
51,23,2,Canned Soda,[Mountain Dew],$2.18,2.18,1.09
2823,1121,3,Bottled Water,NaN,$3.27,3.27,1.09
818,338,3,Bottled Water,NaN,$3.27,3.27,1.09

In [204]:
#aquí mostramos el item con el precio unitario más alto
most_expensive_item = chipo.loc[max_unit_price_idx, 'item_name']
most_expensive_item  #hay muchos, entiendo toma la primera aparición o así.

'Steak Salad Bowl'

In [ ]:
#con Grouby, agrupaciones
chipo.groupby('item_name')['item_price_float'].max()

### Paso 4. ¿Cuántos productos cuestan más de 10,00 dólares?

In [ ]:
chipo['item_price_float'].value_counts() > 10.00

In [167]:
count_above_10 = (chipo['item_price_float'] > 10.00).sum()
print (f'hay {count_above_10} productos por encima de $10.00 en la lista')

hay 1130 productos por encima de $10.00 en la lista

In [ ]:
chipo_filtrado = chipo[chipo['item_price_float'] > 10.0]  #otra forma, imprimiendo
chipo_filtrado.sort_values('item_price_float')

### Paso 5. ¿Cuál es el precio de cada artículo?
###### imprimir un marco de datos con sólo dos columnas nombre_artículo y precio_artículo

In [ ]:
chipo.head()

In [181]:
chipo_resume = chipo ['item_name']
print(type(chipo_resume))

<class 'pandas.core.series.Series'>

In [ ]:
chipo_resume = chipo [['item_name','item_price']]
chipo_resume.head()

In [ ]:
print(type(chipo_resume))

### Paso 6. Ordenar por el nombre del artículo

In [192]:
chipo_resume.sort_values('item_name')

              item_name item_price
3389  6 Pack Soft Drink    $12.98
341   6 Pack Soft Drink     $6.49
1849  6 Pack Soft Drink     $6.49
1860  6 Pack Soft Drink     $6.49
2713  6 Pack Soft Drink     $6.49
...                 ...        ...
2384  Veggie Soft Tacos     $8.75
781   Veggie Soft Tacos     $8.75
2851  Veggie Soft Tacos     $8.49
1699  Veggie Soft Tacos    $11.25
1395  Veggie Soft Tacos     $8.49

[4622 rows x 2 columns]

### Paso 7. ¿Cuál fue la cantidad pedida del artículo más caro? 2 formas

In [193]:
chipo.sort_values('item_price_float', ascending = False) #lo llamo de nuevo para comprobar

,order_id,quantity,item_name,choice_description,item_price,item_price_float
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25,44.25
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25,35.25
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00,35.00
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00,35.00
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75,33.75
...,...,...,...,...,...,...
1057,435,1,Canned Soda,[Mountain Dew],$1.09,1.09
117,51,1,Canned Soda,[Diet Dr. Pepper],$1.09,1.09
2562,1014,1,Canned Soda,[Coca Cola],$1.09,1.09
2544,1009,1,Canned Soda,[Diet Coke],$1.09,1.09
2545,1009,1,Bottled Water,NaN,$1.09,1.09

In [205]:
# max_price_quantity = chipo.loc[chipo['item_price_float'].idxmax(), 'quantity']
chipo.loc[chipo['item_price_float'].idxmax(), 'quantity']

np.int64(15)

### Paso 8. ¿Cuántas veces pidió ensalada de verduras?

In [ ]:
d

### Paso 9. ¿Cuántas veces pidió alguien más de un refresco en lata?